# Generated by Django 4.0.5 on 2022-10-08 02:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_remove_staffpage_ministry_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpage',
            name='ministry_links',
            field=wagtail.fields.StreamField([('ministries', wagtail.blocks.StructBlock([('headerLink', wagtail.blocks.PageChooserBlock())]))], blank=True, null=True, use_json_field=False),
        ),
    ]
