# Generated by Django 4.0.5 on 2022-10-08 01:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_staffpage_staff_bio_staffpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpage',
            name='staff_bio',
            field=wagtail.fields.StreamField([('staff_bio', wagtail.blocks.StructBlock([('staffPosition', wagtail.blocks.CharBlock(blank=True, form_classname='Staff Position', required=False))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
