# Generated by Django 4.0.5 on 2022-10-08 01:16

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staffpage_staff_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpage',
            name='staff_bio',
            field=wagtail.fields.StreamField([('staff_bio', wagtail.blocks.StructBlock([('biography', wagtail.blocks.RichTextBlock(Required=False, help_text='Add the page content here')), ('fun_facts', wagtail.blocks.RichTextBlock(Required=False, help_text='Add the page content here'))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
