# Generated by Django 4.0.5 on 2022-10-08 01:25

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_staffpage_staff_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpage',
            name='fun_facts',
            field=wagtail.fields.RichTextField(default='This is just a placeholder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffpage',
            name='ministry_links',
            field=wagtail.fields.StreamField([('ministries', wagtail.blocks.StructBlock([('headerLink', wagtail.blocks.URLBlock(required=False))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='staff_bio',
            field=wagtail.fields.RichTextField(default='This is just a placeholder'),
            preserve_default=False,
        ),
    ]
