# Generated by Django 4.0.5 on 2022-10-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_staffpage_fun_facts_staffpage_ministry_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpage',
            name='test_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
