# Generated by Django 4.0.5 on 2023-07-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_staffpage_ministry_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpage',
            name='component',
            field=models.CharField(choices=[('CircleImageStacked', 'CircleImageStacked')], default='CircleImageStacked', max_length=50),
        ),
        migrations.AddField(
            model_name='staffpage',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
