# Generated by Django 4.0.5 on 2022-06-21 00:09

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.table_block.blocks
import wagtail.blocks
import wagtail.fields
import wagtail_headless_preview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtaildocs', '0012_uploadeddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamFields',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_headless_preview.models.HeadlessPreviewMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('displaySectionTitle', models.BooleanField(default=True)),
                ('sectionHeader', models.CharField(blank=True, max_length=150, null=True)),
                ('content', wagtail.fields.RichTextField(blank=True, null=True)),
                ('subsections', wagtail.fields.StreamField([('paragraph', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(blank=True, form_classname='Section Header', required=False)), ('displayHeader', wagtail.blocks.BooleanBlock(required=False)), ('content', wagtail.blocks.RichTextBlock(Required=True, help_text='Add the page content here')), ('isHeaderLink', wagtail.blocks.BooleanBlock(form_classname='Is Header a Link', required=False)), ('headerLink', wagtail.blocks.URLBlock(required=False))])), ('table_block', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(blank=True, form_classname='Section Header', required=False)), ('displayHeader', wagtail.blocks.BooleanBlock(required=False)), ('isHeaderLink', wagtail.blocks.BooleanBlock(form_classname='Is Header a Link', required=False)), ('headerLink', wagtail.blocks.URLBlock(required=False)), ('content', wagtail.contrib.table_block.blocks.TableBlock())]))], blank=True, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='about.streamfields')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
