# Generated by Django 4.0.6 on 2022-07-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('about', '0002_alter_pagecontent_subsections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StreamFields',
            new_name='StreamFieldsPage',
        ),
    ]
