# Generated by Django 4.0.5 on 2022-10-02 04:32

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_streamfields_streamfieldspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='subsections',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(blank=True, form_classname='Section Header', required=False)), ('displayHeader', wagtail.blocks.BooleanBlock(required=False)), ('content', wagtail.blocks.RichTextBlock(Required=True, help_text='Add the page content here')), ('isHeaderLink', wagtail.blocks.BooleanBlock(form_classname='Is Header a Link', required=False)), ('headerLink', wagtail.blocks.URLBlock(required=False))])), ('logo_block', wagtail.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock(Required=True))])), ('document_block', wagtail.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock(required=False))]))], blank=True, null=True),
        ),
    ]
